### ISSUE TITLE
PHP Parse error:  syntax error, unexpected integer "881791801567105035", expecting ")" in /root/ShadowsDash/require/page.php on line 13

### ISSUE THREAD

**Issue by MD211211** [ShadowsDash/ShadowsDash#2]
PHP Parse error:  syntax error, unexpected integer "881791801567105035", expecting ")" in /root/ShadowsDash/require/page.php on line 13

**Comment by MD211211** [comment]
default issue is: PHP Warning:  Undefined array key "user" in /root/ShadowsDash/require/page.php on line 13
PHP Warning:  Attempt to read property "id" on null in /root/ShadowsDash/require/page.php on line 13
PHP Fatal error:  Uncaught Error: Call to a member function fetch_array() on bool in /root/ShadowsDash/require/page.php:13
Stack trace:
#0 /root/ShadowsDash/index.php(2): require()
#1 {main}
  thrown in /root/ShadowsDash/require/page.php on line 13

**Comment by shadowdevfr** [comment]
Try to update 😁
